# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Docker Container mit PHP
      - image: circleci/php:7.1-browsers
      

    working_directory: ~/repo

    steps:
      #hole den neuesten Code
      - checkout

      - run: composer install -n --prefer-dist
        
      # run behat tests
      - run: vendor/bin/behat